### ISSUE TITLE
Add support for system monospace / serif fonts

### ISSUE THREAD

**Issue by fuzzyfox** [csstools/system-font-css#13]
Right now this only accounts for sans-serif fonts, it would be nice to also have support for serif and monospace... possibly with the font names `system-ui-serif` and `system-ui-mono`

**Comment by rhysburnie** [comment]
Personally for explicit font styles I would define the names using the generic font families: `serif` and `monospace` since system font is the generic `system-ui` generic font family and `sans-serif` if you want an explicit sans-serif (since `system-ui` could be any family depending on platform / user choice - defaults tend to be sans-serif obviously).

**Comment by zachleat** [comment]
Yeah, this enhancement is super unlikely to happen here I think given the maintenance allotment we’re providing here. Feel free to create a new project for those!

I’m going to close this. If the other maintainers have objections, please reopen.

**Comment by matthew-dean** [comment]
Dang, I came here with this same question e.g. a cross-platform stack for serif fonts that are used across each native system. Although I guess the difference is that system fonts aren't used for the UI in those OSes?
