### ISSUE TITLE
Standardization is happening around `system-ui`

### ISSUE THREAD

**Issue by zachleat** [csstools/system-font-css#3]
Not saying you should rename your family name here (up for discussion?), but either way the README needs updated to replace the section about `system` with `system-ui`.

Is this project intended to be a polyfill for `system-ui`?

https://drafts.csswg.org/css-fonts-4/#system-ui-def
More resources here: https://github.com/Fyrd/caniuse/issues/2918

**Comment by jonathantneal** [comment]
Yes, once upon a time, this was just an interesting idea. Now there are actual standards happening.

If people still think this repo is useful, I’m happy to tweak it to match the standard. Or if someone wants to make a PR, even better. They could be made a collaborator, too! Otherwise, it’s just an artifact, and I’m happy to delete it to reduce confusion. It was made to show it could be done, and to encourage people to think about the idea — which maybe it did? IDK.

**Comment by zachleat** [comment]
Oh, no, absolutely don’t delete it. Especially considering that it’s linked up from https://css-tricks.com/snippets/css/system-font-stack/ which is so great (and actually overlaps a lot with a blog post that I’m writing now, but didn’t find it until my post was almost done 😭).

Just wanted to get your feeling on it—I’ll PR the change.

**Comment by zachleat** [comment]
For posterity, the PR is here: https://github.com/jonathantneal/system-font-css/pull/4

**Comment by jonathantneal** [comment]
Rebased, merged, published. You’ve been invited as a collaborator and given publish permissions. You can turn them down, of course, if you don’t want to be bothered beyond this PR. I just like when a project escapes the one dev bottleneck.

**Comment by Martin-Pitt** [comment]
Per https://github.com/jonathantneal/system-font-css/issues/7#issuecomment-317015048 this might need to be undone due to actually causing it to override the standard!
